version: '2.1'

services:
  webgoat:
    image: webgoat/webgoat-8.0
    environment:
      - server.tomcat.accesslog.buffered=false
      - server.tomcat.accesslog.enabled=true
    ports:
      - "8080:8080"
#    volumes:
#      - .:/home/webgoat/.webgoat
    command: "java -Djava.security.egd=file:/dev/./urandom -jar /home/webgoat/webgoat.jar --server.port=8080"
